### ISSUE TITLE
Code Along Error

### ISSUE THREAD

**Issue by AlexGZhang2014** [learn-co-curriculum/rails-activerecord-models-and-rails-readme#12]
I git cloned the repo to follow along. I just want to point out that the lesson says "Open up the Rails console by running rails console," but doing that led to an error:

"/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands/console.rb:29:in `block in parse_arguments': invalid option: -b (OptionParser::InvalidOption)"

Running "bundle exec rails console" works just fine, so maybe add that in the lesson.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
