### ISSUE TITLE
Student needs to run bundle install and rails g rspec:install

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/rails-activerecord-models-and-rails-readme#15]
It's not clear from the instructions that the student needs to run the following:
bundle install
rails g rspec:install

The instructions for those two items are worded in the past tense and located in a gray-colored area of the screen with other prerequisites, implying that those steps are already done. Kindly update.

Thank you.

**Comment by FionaDL** [comment]
I agree with Valerie's statement. I would not have known to do that if I had not checked to see if there were any issues with this lab. 

Thank you.

**Comment by atxrenegade** [comment]
I agree. Nothing is more frustrating as a student that to have to debug each lesson before use.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue.
