### ISSUE TITLE
Unable to execute any rspec tests until adding helpers and database_cleaner

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-curriculum/rails-activerecord-models-and-rails-readme#17]
Unable to execute any rspec tests until adding the following files:

rails_helper.rb
spec_helper.rb

and to Gemfile.rb
gem 'database_cleaner', '~> 1.7'

**Comment by schanrai** [comment]
In addition, had to add gem 'capybara'

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue.
