### ISSUE TITLE
Outdated and Terribly Written

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/rails-activerecord-models-and-rails-readme#18]
This lab is a waste of my time. Every time I try to execute something in my terminal, I have to correct some issue with an outdated gem. There's no benefit to adding the spec file in piece by piece. At this point, the curriculum has already covered ActiveRecord/ORMs and this lab is just confusing and a waste of time.

**Comment by quelluomo** [comment]
I could not agree more.

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

Thanks for contributing! 💙
