### ISSUE TITLE
Rails console does not run

### ISSUE THREAD

**Issue by PrincessLaurora** [learn-co-curriculum/rails-activerecord-models-and-rails-readme#19]

**Comment by PrincessLaurora** [comment]
Rails console does not run, this lab is clearly outdated. I spent a lot of time already with the rails g rspec:install issue and now I am not able to use the console due to an error(/usr/local/rvm/gems/ruby-2.6.1/gems/railties-4.2.10/lib/rails/commands/console.rb:29:in `block in parse_arguments': invalid option: -b (OptionParser::InvalidOption). Has anyone else experienced the same issue?

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue.
