### ISSUE TITLE
rake db:migrate orrr rake db:create?

### ISSUE THREAD

**Issue by dwyn** [learn-co-curriculum/rails-activerecord-models-and-rails-readme#9]
About 40%-45% down the page, right after we are instructed to build a `post` class, we are instructed to create a schema file by running `rake db:migrate` but I think it should be `rake db:create`. Once we have updated the migration file, then we are supposed to run `rake db:migrate` so that our schema is updated with the correct table/columns. I could be wrong, but here is the text I am referring to:

"This will get the tests passing, but it still has some weird errors because we need to create a schema file. You can do that by running rake db:migrate. This will create the schema file and clear the warning. Now update the Post spec to test for a Post being created. It should look something like this:"

**Comment by curiositypaths** [comment]
Hi there,

Thank you for taking the time to contribute to our curriculum. 

We updated the read me to state that *there is no need to create a database with rake db:create first. The test suite will create a test database for us when we run our tests*.

Thanks! 💙
